### ISSUE TITLE
There is no progress when I try to export the tagged video data set using "Export Labels" option.

### ISSUE THREAD

**Issue by sachinjha** [IBM/powerai-counting-cars#16]
I have manually tagged 5 frames in my video. As per the documentation in step 1.1  last thing is to export label so that the tagged data set shows up in Datasets section. 

I tried that and its stuck there.. Just shows "Exporting label" for more than an hour. Other's also reported the same issue.

<img width="1249" alt="screen shot 2018-07-25 at 1 49 41 pm" src="https://user-images.githubusercontent.com/891637/43188690-41b8002a-8fe4-11e8-8423-7f4018bf4a71.png">

**Comment by markstur** [comment]
Could you try labelling more objects.  I think there might be a minimum 5 frames and something like 25 labeled objects.  I need to confirm and document it, but would like to hear if that gets you past this problem.

**Comment by sachinjha** [comment]
I labelled 28 objects in 8 frames but don't see any difference. Still stuck at "Exporting Labels"

**Comment by julian-gebhart** [comment]
I am experiencing the same issue while I labelled 77 objects in 5 frames. Would appreciate any hint how to solve it. Thanks!

**Comment by markstur** [comment]
Please open a new issue if you see this problem again.  We had it reproduced and "un-stuck".  You should be able to successfully run now.  If not, I might need to have each stuck account looked into. Sorry for the inconvenience.  Hope the problem is really gone.
