### ISSUE TITLE
Labels will not export

### ISSUE THREAD

**Issue by PatrickWalsh6079** [IBM/powerai-counting-cars#20]
I followed the instructions in the README file and I am stuck on the step "Use the video's Operation button and select Export Labels with the pull-down." I created 10 manual labels of the cars from two snapshots of the video and exported the labels in Video Data Platform. However, the labels have not finished exporting. It has been running for about 10 hours.

**Comment by markstur** [comment]
Hi @PatrickWalsh6079,

Could you try more frames/labels?  5 frames and 25-30 labeled cars was recommended with the version on SuperVessel.

**Comment by BahaaMansour** [comment]
I actually labeled 30 cars on 8 different frames, and still stuck on "Exporting Labels". Manual Labels= 241 
I would really appreciate it if you can fix this issue. <3 Thanks a lot!!

**Comment by PatrickWalsh6079** [comment]
I created 8 tagged frames and 34 labels but it has been exporting for several days now with no resolve.

**Comment by markstur** [comment]
There is an export to zip and import from zip to download/upload your dataset. It's in the UI. Open your dataset to see the export.

Also, I just submitted a PR with one of my labeled datasets. Using that would be skipping a good part of the code pattern, but it might be handy if needed.

**Comment by markstur** [comment]
I've been told the problem should be fixed now.  Please try again (w/ at least 5 frames and 25 labels)

**Comment by frickD** [comment]
Unfortunately I have the same problem. It has been exporting for hours...

**Comment by Mohamed-AH** [comment]
works fine now.
