### ISSUE TITLE
Labels are not exporting

### ISSUE THREAD

**Issue by BahaaMansour** [IBM/powerai-counting-cars#27]
Every time i try to access  "https://ny1.ptopenlab.com/AIVision/index.html#!/datasets"  in GOOGLE CHROME and Firefox and i keep getting
![can no longer access](https://user-images.githubusercontent.com/44228249/49855354-6c000680-fe06-11e8-9a22-7e917ba36c68.png)

When i try to access it visa microsoft edge it gets stuck at this message.
![ai vision](https://user-images.githubusercontent.com/44228249/49855391-8a660200-fe06-11e8-8048-4e00f21b1a4c.png)

Labels are no longer exporting.

**Comment by markstur** [comment]
support team is working on it.  Supervessel is definitely having issues at the moment.

**Comment by BahaaMansour** [comment]
AI Vision has opened again. 
But unfortunately Video Data Platform does not open. 
![video data platform](https://user-images.githubusercontent.com/44228249/50217371-e948ef80-03a1-11e9-85f3-ae2aab62ffd5.png)

**Comment by markstur** [comment]
I can use SuperVessel now.  I had to re-enter my password and not use the saved one.  Not sure if github logins are restored yet.

**Comment by markstur** [comment]
I could not export labels or do autolabelling.  Both start but seem to be stuck.

**Comment by BahaaMansour** [comment]
Update on the issue: 
1. I can access both AI Vision and Video Data Platform. 
2. Exporting labels is still an issue. Nothing is being exported.
![export](https://user-images.githubusercontent.com/44228249/50530426-b7105e00-0b16-11e9-9527-c421752b67b7.png)


Thank you.

**Comment by Moogun** [comment]
Same here. Labels are not being exported.

**Comment by tejasri19** [comment]
> Update on the issue:
> 
>     1. I can access both AI Vision and Video Data Platform.
> 
>     2. Exporting labels is still an issue. Nothing is being exported.
>        ![export](https://user-images.githubusercontent.com/44228249/50530426-b7105e00-0b16-11e9-9527-c421752b67b7.png)
> 
> 
> Thank you.

I counldn't access Video Data Platform. Need help on this!

**Comment by markstur** [comment]
we're still stuck waiting for them to complete the SuperVessel upgrade.

**Comment by markstur** [comment]
There is a new trial registration open here: https://developer.ibm.com/linuxonpower/deep-learning-powerai/vision/access-registration-form/

Sorry about the inconvenience.
