### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by marcellusmontilla** [IBM/powerai-counting-cars#34]
I'm sorry if I have to ask these here. The IBM sales representative in my country does not seem to know what I'm asking. Do you have any idea how much these will cost (rough estimates in your currency will do):
• IBM Power Systems
• IBM Power AI
• IBM PowerAI Vision Technology Preview
• Nimbix Cloud Computing Platform (not IBM, I know)

I need to know if we can afford these beyond the free-trial period.

**Comment by ccalio** [comment]
Please reach out and contact SRINI V. CHITIVELI
Global Offering Manager & Master Inventor
IBM PowerAI Vision  http://ibm.biz/tryPAIV
 E-mail: svchitiv@us.ibm.com

**Comment by stevemart** [comment]
Thanks for chiming in @ccalio ! 

@marcellusmontilla I'm closing this issue -- send an email to Srini and he'll be able to help you out.
