### ISSUE TITLE
Link to PowerAi platform does not work

### ISSUE THREAD

**Issue by manninfrance** [IBM/powerai-counting-cars#35]
All of the URLs under  https://ny1.ptopenlab.com are returning mentioned in the README.md file are getting 404 or other errors

**Comment by markstur** [comment]
we're still waiting for a supervessel and powerai vision upgrade to complete

**Comment by manninfrance** [comment]
It has been upgrading since the 9th of january?

**Comment by markstur** [comment]
I'm not sure if we'll get SuperVessel free trials back.  We'll be updating this in April.  Will hopefully have a clear message on where to get a free trial (if there is any).

**Comment by markstur** [comment]
There is a new trial registration open here: https://developer.ibm.com/linuxonpower/deep-learning-powerai/vision/access-registration-form/

Sorry about the inconvenience.
