### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by FranciscoSola** [IBM/powerai-counting-cars#46]
Hi, I'm trying to run the notebook with my own model but I keep getting the following error when running the inference function:

ConnectionError: HTTPConnectionPool(host='ny1.ptopenlab.com', port=80): Max retries exceeded with url: /powerai-vision-ny/api/dlapis/00b984d5-489d-413e-9e47-c8824eba77ca (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000268B34A09B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Does anybody have any idea about how i can solve it?
Thanks a lot

**Comment by tvotan** [comment]
I also get the same error message like @FranciscoSola  : 
<img width="1227" alt="Screenshot 2020-03-02 at 5 05 33 PM" src="https://user-images.githubusercontent.com/39995527/75694078-3dd74280-5ca8-11ea-95ef-d644b48281de.png">
<img width="1204" alt="Screenshot 2020-03-02 at 5 05 47 PM" src="https://user-images.githubusercontent.com/39995527/75694160-5cd5d480-5ca8-11ea-85fe-997ffcf00936.png">

Anyone here who can help? (Probably no one at IBM cares about this ... I must say that IBM's support is tremendously bad, same issue support like IBM Watson).

**Comment by tvotan** [comment]
I think the link doesn't work:

`# Set this URL to the API endpoint of your deployed model.
POWER_AI_VISION_API_URL = "https://ny1.ptopenlab.com/powerai-vision-ny/api/dlapis/your-guide-here"`

btw, I'm on Python 3.7.6
<img width="1177" alt="Screenshot 2020-03-02 at 5 30 41 PM" src="https://user-images.githubusercontent.com/39995527/75696344-bdb2dc00-5cab-11ea-90d3-e9bee00c427c.png">

**Comment by gcorneau-ibm** [comment]
The prerequisite for this lab is an installed instance of a PowerAI Vision server that you can connect to (and train the source dataset so that you can deploy the model (with an appropriate API).  The "ny1.ptopenlab.com" server is just an example.

**Comment by horeaporutiu** [comment]
@tvotan @FranciscoSola You will need to update the POWER_AI_VISION_API_URL with the deployed model URL. 

It should look something like this: https://vision-poc1.aus.stglabs.ibm.com/visual-insights-v120-prod/api/dlapis/71e4aadc-36-487d-8182-3e67e8e6c

You need a trial version of Maximo Visual Insights to do this. To get a trial version of Maximo Visual Insights, go here: https://www.ibm.com/support/pages/ibm-maximo-visual-inspection

Scroll down to `Give it a try`. 

Hopefully, this helps. Feel free to open the issue back up if this does not resolve it.
