### ISSUE TITLE
PowerAI to Visual Insights

### ISSUE THREAD

**Issue by utkutpcgl** [IBM/powerai-counting-cars#47]
I guess power ai vision has changed its name to visual insights and now it is no more free to access the auto labelling. I want to use especially the auto labelling tool, is there any advice? Thanks.

**Comment by andreAbtahi96** [comment]
Are you using IBM’s machine learning tools to start?

**Comment by gcorneau-ibm** [comment]
If you need access to IBM Visual Insights (the new name for PowerAI Vision):
https://developer.ibm.com/linuxonpower/deep-learning-powerai/vision/#try
One big change is the product now supports both ppc64le as well as x86.

**Comment by andreAbtahi96** [comment]
Sorry, I’m confused

Are you asking me a question ?

**Comment by utkutpcgl** [comment]
No @andreAbtahi96 , I just wanted to auto-label them before dumping them. I found intel CVAT (computer vision anotation tool). It is easier and sufficient for my dataset. Thanks @gcorneau-ibm and @andreAbtahi96.
